/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LandlordRouteImport } from './routes/landlord'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/browse': typeof BrowseRoute
  '/landlord': typeof LandlordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/browse': typeof BrowseRoute
  '/landlord': typeof LandlordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/browse': typeof BrowseRoute
  '/landlord': typeof LandlordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/browse'
    | '/landlord'
    | '/sitemap.xml'
    | '/rooms/$roomId'
    | '/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/browse'
    | '/landlord'
    | '/sitemap.xml'
    | '/rooms/$roomId'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/browse'
    | '/landlord'
    | '/sitemap.xml'
    | '/rooms/$roomId'
    | '/settings/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BrowseRoute: typeof BrowseRoute
  LandlordRoute: typeof LandlordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord': {
      id: '/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  BrowseRoute: BrowseRoute,
  LandlordRoute: LandlordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
